use crate::error::{CALLBACK_DATA_MAX_LEN, PackError, SEP, UnpackError};
use crate::flat_field::FlatField;

/// Compile-time configuration generated by `#[callback_data(prefix = "...")]`.
pub trait CallbackDataConfig {
    /// The literal prefix, e.g. `"xxx"`. Never contains `SEP`.
    const PREFIX: &'static str;
}

/// Top-level callback-data type: has a stable prefix, and — via the
/// `FlatField` bound — a fixed, compile-time-known list of flattened
/// tokens for its fields (including nested `#[derive(FlatField)]` types
/// and enums).
pub trait CallbackDataTrait: CallbackDataConfig + FlatField + Sized {
    /// The id of the Telegram user this callback "belongs to", if the type
    /// has a field marked `#[callback_data(owner)]`. `None` if no such
    /// field exists.
    ///
    /// This is the *entire* contract — this crate has no opinion on what
    /// you do with a mismatch (response text, alert flag, logging,
    /// localization). Compare it yourself in your own filter/middleware.
    fn owner_id(&self) -> Option<i64> {
        None
    }

    /// Pack `self` into a Telegram-safe `callback_data` string:
    /// `PREFIX:field1:field2:...`.
    ///
    /// Performs a round-trip self-check: if the packed string can't be
    /// unpacked back into an equivalent set of tokens, this returns
    /// `PackError::RoundTripMismatch` instead of silently producing a
    /// broken button.
    fn pack(&self) -> Result<String, PackError> {
        if Self::PREFIX.contains(SEP) {
            // This is really a static invariant the derive macro should
            // guarantee at compile time, but we double check defensively
            // since PREFIX is user-supplied text.
            return Err(PackError::ContainsSeparator {
                value: Self::PREFIX.to_string(),
                sep: SEP,
            });
        }

        let mut tokens = vec![Self::PREFIX.to_string()];
        self.pack_into(&mut tokens)?;
        let packed = tokens.join(SEP);

        if packed.len() > CALLBACK_DATA_MAX_LEN {
            return Err(PackError::TooLong {
                len: packed.len(),
                max: CALLBACK_DATA_MAX_LEN,
                packed,
            });
        }

        // Self-check: what we just packed must unpack back cleanly.
        if let Err(err) = Self::unpack(&packed) {
            return Err(PackError::RoundTripMismatch(Box::new(err)));
        }

        Ok(packed)
    }

    /// Parse a raw `callback_data` string (as received from Telegram) back
    /// into `Self`. Never panics — always returns `Err` on mismatched
    /// prefix, wrong token count, or unparsable tokens (e.g. an outdated
    /// button from before a field was added/removed/retyped).
    fn unpack(raw: &str) -> Result<Self, UnpackError> {
        if raw.is_empty() {
            return Err(UnpackError::Empty);
        }

        let all_tokens: Vec<String> = raw.split(SEP).map(str::to_owned).collect();
        let expected_len = 1 + Self::TOKEN_COUNT;

        if all_tokens.len() != expected_len {
            return Err(UnpackError::TokenCountMismatch {
                expected: expected_len,
                got: all_tokens.len(),
            });
        }

        let mut iter = all_tokens.into_iter();
        let prefix = iter.next().ok_or(UnpackError::Empty)?;
        if prefix != Self::PREFIX {
            return Err(UnpackError::PrefixMismatch {
                expected: Self::PREFIX.to_string(),
                got: prefix,
            });
        }

        Self::unpack_from(&mut iter)
    }

    /// `Self::as_filter()` — a `telers::Filter` that matches an update
    /// whose callback query unpacks into `Self`. Requires the `telers`
    /// feature. See [`crate::CallbackDataFilter`] for what it does with
    /// the context (`"callback_data"` and `OWNER_ID_CONTEXT_KEY`).
    #[cfg(feature = "telers")]
    fn as_filter() -> crate::telers_support::CallbackDataFilter<Self> {
        crate::telers_support::CallbackDataFilter::new()
    }
}

// NOTE: no blanket `impl<T> CallbackDataTrait for T where ...` here on
// purpose. The `#[callback_data(prefix = "...")]` macro generates an
// explicit `impl CallbackDataTrait for #name { ... }` per type instead, so
// it can override `owner_id()` for types with a `#[callback_data(owner)]`
// field. A blanket impl would make that impossible (conflicting/coherence
// error) since a concrete impl can't coexist with a blanket one covering
// the same type.
